"""rename passkey credentials, drop is_totp_enabled, add auth_events

Revision ID: 66b6b3289296
Revises: f8b7eda62738
Create Date: 2026-07-21 19:05:13.955366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66b6b3289296'
down_revision: Union[str, None] = 'f8b7eda62738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('method', sa.Enum('PASSKEY', 'TOTP_PASSWORD', name='auth_method'), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passkey_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('credential_id', sa.String(length=512), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('device_type', sa.Enum('RESIDENT', 'NON_RESIDENT', name='device_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passkey_credentials_credential_id'), 'passkey_credentials', ['credential_id'], unique=True)
    op.drop_index('ix_webauthn_credentials_credential_id', table_name='webauthn_credentials')
    op.drop_table('webauthn_credentials')
    op.drop_column('users', 'is_totp_enabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_totp_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_table('webauthn_credentials',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('credential_id', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('public_key', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('sign_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transports', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('device_name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='webauthn_credentials_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='webauthn_credentials_pkey')
    )
    op.create_index('ix_webauthn_credentials_credential_id', 'webauthn_credentials', ['credential_id'], unique=True)
    op.drop_index(op.f('ix_passkey_credentials_credential_id'), table_name='passkey_credentials')
    op.drop_table('passkey_credentials')
    op.drop_table('auth_events')
    # ### end Alembic commands ###
