"""add is_simulated to auth_events

Revision ID: a9c958b3c58d
Revises: 37ac3ca2033f
Create Date: 2026-07-26 16:31:42.245388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9c958b3c58d'
down_revision: Union[str, None] = '37ac3ca2033f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Manually adjusted: server_default backfills every real historical row
    # (accumulated well before this column existed) as not-simulated, which
    # is accurate - all new rows always pass an explicit value going forward.
    op.add_column(
        'auth_events',
        sa.Column('is_simulated', sa.Boolean(), nullable=False, server_default=sa.false()),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_events', 'is_simulated')
    # ### end Alembic commands ###
